services:
  redis_service:
    image: "redis:7.0.10-bullseye"
    networks:
      - backend_network
    volumes:
      - "redis_volume:/data"
  web_service:
    build: ./web
    ports:
      - "80:8000"
    environment:
      REDIS_URL: "redis://redis_service:6379"
    networks:
      - backend_network
    depends_on:
      - redis_service
    command: "gunicorn page_tracker.app:app --bind 0.0.0.0:8000"

networks:
  backend_network:


volumes:
  redis_volume:
