services:
  redis_service:
    image: "redis:7.0.10-bullseye"
    networks:
      - backend_network
    volumes:
      - "redis_volume:/data"
  web_service:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: "redis://redis_service:6379"
    networks:
      - backend_network
    depends_on:
      - redis_service

networks:
  backend_network:


volumes:
  redis_volume:
