services:
    mysql:
        image: mysql:latest
        container_name: mysql-container
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - mysql-volume:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mysql-volume:
        external: false
