services:
    mysql:
        image: mysql:latest
        container_name: mysql-mappings
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: --init-file /data/application/${INIT_SQL}
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./${INIT_SQL}:/data/application/${INIT_SQL}
        ports:
            - "3306:3306"

volumes:
    mysql-volume:
        external: false
