services:
    mysql:
        image: mysql:latest
        container_name: mysql-mappings
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        command: --init-file /data/application/one-to-one-uni-init.sql
        volumes:
            - mysql-volume:/var/lib/mysql
            - ./one-to-one-uni-init.sql:/data/application/one-to-one-uni-init.sql
        ports:
            - "3306:3306"

volumes:
    mysql-volume:
        external: false
